# Generated by Django 5.2.8 on 2026-03-18 11:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contract_Emp_App', '0001_initial'),
        ('HRM_App', '0176_dasauthcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='billing_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Agreed billing amount for this requirement', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='billing_model',
            field=models.CharField(blank=True, choices=[('one_time', 'One-Time'), ('monthly', 'Monthly Recurring')], help_text='Billing model for this requirement: one-time or monthly recurring', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='ClientBillingCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_month', models.PositiveIntegerField(help_text='Billing cycle number (1 = first month, 2 = second month, etc.)')),
                ('billing_amount', models.DecimalField(decimal_places=2, help_text='Amount to be billed for this cycle', max_digits=12)),
                ('due_date', models.DateField(blank=True, help_text='Date by which payment is due', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_date', models.DateField(blank=True, help_text='Date when payment was actually received', null=True)),
                ('payment_reference', models.CharField(blank=True, help_text='Transaction ID, cheque number, or any payment reference', max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('joining_details', models.ForeignKey(help_text='The candidate joining record this billing cycle belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='billing_cycles', to='HRM_App.clientcandidatejoininghistory')),
            ],
            options={
                'ordering': ['cycle_month'],
                'unique_together': {('joining_details', 'cycle_month')},
            },
        ),
    ]
