# Generated by Django 5.2.8 on 2026-03-30 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contract_Emp_App', '0002_requirement_billing_amount_requirement_billing_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientbillingcycle',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total amount paid so far (supports partial payments)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='clientbillingcycle',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially Paid'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
