# Generated by Django 5.2.8 on 2026-04-01 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contract_Emp_App', '0003_add_paid_amount_to_billing_cycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientbillingcycle',
            name='candidate_paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Actual salary amount paid to candidate so far', max_digits=12),
        ),
        migrations.AddField(
            model_name='clientbillingcycle',
            name='candidate_payout_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Salary amount due to candidate (includes taxes/PF)', max_digits=12),
        ),
        migrations.AddField(
            model_name='clientbillingcycle',
            name='payout_date',
            field=models.DateField(blank=True, help_text='Date when salary was paid to candidate', null=True),
        ),
        migrations.AddField(
            model_name='clientbillingcycle',
            name='payout_reference',
            field=models.CharField(blank=True, help_text='Salary transaction reference/UTR number', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientbillingcycle',
            name='payout_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially Paid'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
    ]
