# Generated by Django 5.2.8 on 2026-04-20 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contract_Emp_App', '0004_clientbillingcycle_candidate_paid_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='requirement_status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', help_text='Status of the requirement', max_length=20),
        ),
    ]
