# Generated by Django 5.2.7 on 2026-06-02 05:55

import django.db.models.deletion
import whatsapp_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.CharField(max_length=6)),
                ('otp_type', models.CharField(choices=[('signup', 'Signup'), ('forgot_password', 'Forgot Password')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_verified', models.BooleanField(default=False)),
                ('user_data', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flask_bot_url', models.URLField(default='http://localhost:5000', max_length=500)),
                ('flask_server_url', models.URLField(blank=True, max_length=500, null=True)),
                ('flask_auth_token', models.CharField(default='super_secret_flask_token_123', max_length=255)),
                ('flask_text_send_path', models.CharField(default='/send-message', max_length=255)),
                ('crm_webhook_url', models.URLField(default='http://localhost:8000/api/whatsapp/events/', max_length=500)),
                ('crm_api_token', models.CharField(default='super_secret_crm_token_123', max_length=255)),
                ('whatsapp_api_token', whatsapp_app.models.EncryptedTextField(blank=True, null=True)),
                ('whatsapp_api_token_start_date', models.DateField(blank=True, null=True)),
                ('whatsapp_api_token_expire_date', models.DateField(blank=True, null=True)),
                ('phone_number_id', models.CharField(blank=True, max_length=100, null=True)),
                ('whatsapp_business_account_id', models.CharField(blank=True, max_length=100, null=True)),
                ('whatsapp_app_id', models.CharField(blank=True, max_length=100, null=True)),
                ('whatsapp_app_name', models.CharField(blank=True, max_length=100, null=True)),
                ('webhook_verify_token', models.CharField(default='my_secret_token_123', max_length=100)),
                ('gemini_api_key', whatsapp_app.models.EncryptedCharField(blank=True, max_length=255, null=True)),
                ('is_ai_enabled', models.BooleanField(default=False)),
                ('verification_status', models.CharField(choices=[('VERIFIED', 'Verified'), ('NOT_VERIFIED', 'Not Verified'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WhatsApp Configuration',
                'verbose_name_plural': 'WhatsApp Configurations',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('EMPLOYEE', 'Employee'), ('MANAGER', 'Manager')], default='ADMIN', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('theme_preference', models.CharField(choices=[('light', 'Light Mode'), ('dark', 'Dark Mode'), ('auto', 'Auto/System Default')], default='auto', max_length=10)),
                ('is_online', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('team_lead', models.ForeignKey(blank=True, help_text='Team Lead for this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(default='en', max_length=10)),
                ('broadcast', models.BooleanField(default=True)),
                ('sms', models.BooleanField(default=True)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('PENDING', 'Pending'), ('SOLVED', 'Solved')], default='OPEN', max_length=20)),
                ('last_message', models.TextField(blank=True, null=True)),
                ('last_message_time', models.DateTimeField(blank=True, null=True)),
                ('last_message_received_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('unread_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_contacts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contact',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('variables', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('RUNNING', 'Running'), ('SENDING', 'Sending'), ('SENT', 'Sent'), ('STOPPED', 'Stopped'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='DRAFT', max_length=20)),
                ('total_contacts', models.IntegerField(default=0)),
                ('total_sent', models.IntegerField(default=0)),
                ('total_failed', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL)),
                ('contacts', models.ManyToManyField(related_name='campaigns', to='whatsapp_app.contact')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoginSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jti', models.UUIDField(unique=True)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('device_name', models.CharField(blank=True, max_length=255)),
                ('browser', models.CharField(blank=True, max_length=255)),
                ('os', models.CharField(blank=True, max_length=255)),
                ('location_city', models.CharField(blank=True, max_length=255)),
                ('location_country', models.CharField(blank=True, max_length=255)),
                ('is_current', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('logged_in_at', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('sender', models.CharField(max_length=50)),
                ('direction', models.CharField(choices=[('INCOMING', 'Incoming'), ('OUTGOING', 'Outgoing')], default='OUTGOING', max_length=20)),
                ('status', models.CharField(choices=[('Sent', 'Sent'), ('Delivered', 'Delivered'), ('Read', 'Read'), ('Failed', 'Failed'), ('Waiting', 'Waiting')], default='Waiting', max_length=20)),
                ('provider_message_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('document', 'Document'), ('template', 'Template')], default='text', max_length=20)),
                ('media_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('caption', models.TextField(blank=True, null=True)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('buttons', models.JSONField(blank=True, null=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='whatsapp_app.campaign')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='whatsapp_app.contact')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('language', models.CharField(default='en_US', max_length=20)),
                ('category', models.CharField(choices=[('MARKETING', 'Marketing'), ('UTILITY', 'Utility'), ('AUTHENTICATION', 'Authentication')], max_length=20)),
                ('header_type', models.CharField(default='NONE', max_length=20)),
                ('header_text', models.CharField(blank=True, max_length=60, null=True)),
                ('body', models.TextField()),
                ('sample_values', models.JSONField(blank=True, default=dict)),
                ('footer_text', models.CharField(blank=True, max_length=60, null=True)),
                ('buttons', models.JSONField(blank=True, default=list)),
                ('variables', models.JSONField(blank=True, default=list)),
                ('variables_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='whatsapp_app.messagetemplate'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_message', 'New Message'), ('unread_message', 'Unread Message'), ('message_read', 'Message Read'), ('system_alert', 'System Alert'), ('agent_assigned', 'Agent Assigned')], default='new_message', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('contact_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('message_id', models.CharField(blank=True, help_text='Provider message ID for deduplication', max_length=255, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='Null means broadcast to all agents', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=255, unique=True)),
                ('language', models.CharField(default='en', max_length=20)),
                ('category', models.CharField(blank=True, default='MARKETING', max_length=50)),
                ('header_type', models.CharField(default='NONE', max_length=20)),
                ('header_text', models.CharField(blank=True, max_length=60, null=True)),
                ('body_text', models.TextField()),
                ('sample_values', models.JSONField(blank=True, default=dict)),
                ('footer_text', models.CharField(blank=True, max_length=60, null=True)),
                ('buttons', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PAUSED', 'Paused'), ('DISABLED', 'Disabled')], default='PENDING_REVIEW', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_synced_at'],
                'indexes': [models.Index(fields=['template_name'], name='whatsapp_wh_templat_7b27c4_idx'), models.Index(fields=['status'], name='whatsapp_wh_status_69f18b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['user', 'phone_number'], name='contact_user_id_5e3129_idx'),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(fields=('user', 'phone_number'), name='unique_contact_phone_per_user'),
        ),
        migrations.AddIndex(
            model_name='messagetemplate',
            index=models.Index(fields=['name'], name='whatsapp_me_name_f76507_idx'),
        ),
        migrations.AddIndex(
            model_name='messagetemplate',
            index=models.Index(fields=['category'], name='whatsapp_me_categor_603642_idx'),
        ),
        migrations.AddIndex(
            model_name='messagetemplate',
            index=models.Index(fields=['status'], name='whatsapp_me_status_ec88e1_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_read', 'created_at'], name='whatsapp_no_is_read_fb22f7_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['contact_phone'], name='whatsapp_no_contact_a82f41_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['message_id'], name='whatsapp_no_message_f8ebd4_idx'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('message_id__isnull', False)), fields=('message_id', 'notification_type'), name='unique_notification_per_message'),
        ),
    ]


