# Generated by Django 5.2.7 on 2026-06-02 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contact',
            name='unique_contact_phone_per_user',
        ),
        migrations.RemoveIndex(
            model_name='contact',
            name='contact_user_id_5e3129_idx',
        ),
        migrations.AddField(
            model_name='campaign',
            name='whatsapp_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='whatsapp_app.whatsappconfig'),
        ),
        migrations.AddField(
            model_name='contact',
            name='whatsapp_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='whatsapp_app.whatsappconfig'),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='whatsapp_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_templates', to='whatsapp_app.whatsappconfig'),
        ),
        migrations.AddField(
            model_name='notification',
            name='whatsapp_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='whatsapp_app.whatsappconfig'),
        ),
        migrations.AddField(
            model_name='whatsappconfig',
            name='name',
            field=models.CharField(default='Default WhatsApp', max_length=255),
        ),
        migrations.AddField(
            model_name='whatsapptemplate',
            name='whatsapp_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_templates', to='whatsapp_app.whatsappconfig'),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='whatsapptemplate',
            name='template_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['user', 'phone_number', 'whatsapp_config'], name='contact_user_id_9417fb_idx'),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(fields=('user', 'phone_number', 'whatsapp_config'), name='unique_contact_phone_config_per_user'),
        ),
        migrations.AddConstraint(
            model_name='messagetemplate',
            constraint=models.UniqueConstraint(fields=('name', 'whatsapp_config'), name='unique_messagetemplate_name_per_config'),
        ),
        migrations.AddConstraint(
            model_name='whatsapptemplate',
            constraint=models.UniqueConstraint(fields=('template_name', 'whatsapp_config'), name='unique_whatsapptemplate_name_per_config'),
        ),
    ]


