# Generated by Django 5.2.7 on 2026-06-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_app', '0002_remove_contact_unique_contact_phone_per_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetemplate',
            name='header_media',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='meta_media_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='uploaded_preview_image',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='whatsapptemplate',
            name='header_media',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='whatsapptemplate',
            name='meta_media_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='whatsapptemplate',
            name='uploaded_preview_image',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]


