# Generated by Django 5.2.7 on 2026-06-12 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_app', '0003_messagetemplate_header_media_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='error_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='error_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='error_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='meta_trace_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]


