# Generated by Django 5.2.7 on 2026-06-16 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_app', '0004_message_error_code_message_error_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='error_code',
        ),
        migrations.RemoveField(
            model_name='message',
            name='error_details',
        ),
        migrations.RemoveField(
            model_name='message',
            name='error_title',
        ),
        migrations.RemoveField(
            model_name='message',
            name='meta_trace_id',
        ),
        migrations.AddField(
            model_name='whatsappconfig',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_configs', to=settings.AUTH_USER_MODEL),
        ),
    ]


