# Generated by Django 5.2.7 on 2026-06-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_app', '0005_remove_message_error_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappconfig',
            name='crm_api_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='whatsappconfig',
            name='crm_webhook_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]


