# Generated by Django 5.2.7 on 2026-06-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_app', '0006_alter_whatsappconfig_crm_api_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetemplate',
            name='header_media',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='uploaded_preview_image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='whatsapptemplate',
            name='header_media',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='whatsapptemplate',
            name='uploaded_preview_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]


