# Generated by Django 5.2.7 on 2026-06-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_app', '0007_alter_messagetemplate_header_media_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetemplate',
            name='header_media',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='uploaded_preview_image',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='whatsapptemplate',
            name='header_media',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='whatsapptemplate',
            name='uploaded_preview_image',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]


