# Generated by Django 5.2.7 on 2026-06-24 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_app', '0008_alter_messagetemplate_header_media_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='customer_service_window_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='is_service_window_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='last_customer_message_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]


