# Generated by Django 5.2.7 on 2026-06-29 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_app', '0010_category_subcategory_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.TextField(help_text='Comma-separated list of keywords')),
                ('reply_text', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('whatsapp_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autoreplies', to='whatsapp_app.whatsappconfig')),
            ],
            options={
                'verbose_name_plural': 'Auto Replies',
                'ordering': ['-created_at'],
            },
        ),
    ]


