# Generated by Django 5.2.7 on 2026-06-30 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_app', '0011_autoreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='aria_journey_stage',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='aria_last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='aria_user_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]


