# Generated by Django 5.2.7 on 2026-07-02 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_app', '0012_contact_aria_journey_stage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assistant_name', models.CharField(default='AI Assistant', max_length=100)),
                ('business_name', models.CharField(default='My Business', max_length=100)),
                ('personality', models.CharField(default='Support', max_length=100)),
                ('tone', models.CharField(default='Friendly', max_length=100)),
                ('primary_language', models.CharField(default='en', max_length=20)),
                ('prompt', models.TextField(blank=True, null=True)),
                ('system_prompt', models.TextField(blank=True, null=True)),
                ('conversation_behaviours', models.JSONField(blank=True, default=list)),
                ('lead_collection', models.JSONField(blank=True, default=list)),
                ('auto_replies', models.JSONField(blank=True, default=list)),
                ('context_window_size', models.IntegerField(default=15)),
                ('fallback_rule', models.CharField(default='transfer', max_length=50)),
                ('confidence_threshold', models.IntegerField(default=70)),
                ('human_handoff_alert', models.BooleanField(default=True)),
                ('primary_color', models.CharField(default='#6366f1', max_length=20)),
                ('widget_position', models.CharField(default='right', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('whatsapp_config', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_config', to='whatsapp_app.whatsappconfig')),
            ],
            options={
                'verbose_name_plural': 'AI Configurations',
            },
        ),
    ]


