# Generated by Django 5.2.7 on 2026-07-03 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_app', '0011_autoreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoreply',
            name='buttons',
            field=models.JSONField(blank=True, default=list),
        ),
    ]


