# Generated by Django 5.2.7 on 2026-07-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_app', '0015_autoreply_buttons'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoreply',
            name='media',
            field=models.ImageField(blank=True, help_text='Optional media (e.g. QR code) to send with the auto-reply', null=True, upload_to='autoreplies/'),
        ),
    ]


