# Generated by Django 5.2.7 on 2026-07-06 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_app', '0014_aiconfig_faqs_aiconfig_websites_knowledgedocument'),
        ('whatsapp_app', '0016_autoreply_media'),
    ]

    operations = [
    ]


