# Generated by Django 5.2.7 on 2026-07-09 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_app', '0018_alter_contact_phone_number_alter_message_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('automation_type', models.CharField(choices=[('FOLLOW_UP', 'Follow-up'), ('REMINDER', 'Reminder')], max_length=20)),
                ('action_type', models.CharField(max_length=20)),
                ('details', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_logs', to='whatsapp_app.contact')),
                ('whatsapp_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_logs', to='whatsapp_app.whatsappconfig')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FollowUpWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_up_workflows', to=settings.AUTH_USER_MODEL)),
                ('whatsapp_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_up_workflows', to='whatsapp_app.whatsappconfig')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FollowUpStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField()),
                ('delay_seconds', models.IntegerField()),
                ('media_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_up_steps', to='whatsapp_app.messagetemplate')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='whatsapp_app.followupworkflow')),
            ],
            options={
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='FollowUpContactState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('next_execution_time', models.DateTimeField()),
                ('retry_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_up_states', to='whatsapp_app.contact')),
                ('current_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='whatsapp_app.followupstep')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_states', to='whatsapp_app.followupworkflow')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ReminderCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('WEBINAR', 'Webinar'), ('EVENT', 'Event'), ('MEETING', 'Meeting'), ('APPOINTMENT', 'Appointment'), ('DEMO', 'Demo'), ('CUSTOM', 'Custom')], max_length=20)),
                ('event_title', models.CharField(max_length=255)),
                ('event_date_time', models.DateTimeField()),
                ('time_zone', models.CharField(default='UTC', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contacts', models.ManyToManyField(related_name='reminder_campaigns', to='whatsapp_app.contact')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_campaigns', to=settings.AUTH_USER_MODEL)),
                ('whatsapp_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_campaigns', to='whatsapp_app.whatsappconfig')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReminderSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timing_type', models.CharField(choices=[('7_DAYS_BEFORE', '7 days before'), ('3_DAYS_BEFORE', '3 days before'), ('1_DAY_BEFORE', '1 day before'), ('6_HOURS_BEFORE', '6 hours before'), ('1_HOUR_BEFORE', '1 hour before'), ('CUSTOM', 'Custom timing')], max_length=30)),
                ('custom_minutes_before', models.IntegerField(blank=True, null=True)),
                ('media_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('reminder_campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='whatsapp_app.remindercampaign')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_schedules', to='whatsapp_app.messagetemplate')),
            ],
        ),
        migrations.CreateModel(
            name='ReminderExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('retry_count', models.IntegerField(default=0)),
                ('execution_time', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_executions', to='whatsapp_app.contact')),
                ('reminder_campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='whatsapp_app.remindercampaign')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='whatsapp_app.reminderschedule')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]


