# Generated by Django 5.2.7 on 2026-07-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_app', '0019_automationlog_followupworkflow_followupstep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconfig',
            name='api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aiconfig',
            name='llm_provider',
            field=models.CharField(default='openai', max_length=50),
        ),
        migrations.AddField(
            model_name='aiconfig',
            name='model_name',
            field=models.CharField(default='gpt-4o-mini', max_length=100),
        ),
        migrations.AlterField(
            model_name='whatsappconfig',
            name='is_ai_enabled',
            field=models.BooleanField(default=True),
        ),
    ]


