# Generated by Django 5.2.7 on 2026-07-31 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_app', '0020_aiconfig_api_key_aiconfig_llm_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='followupstep',
            name='template_variables',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='remindercampaign',
            name='alternate_dates',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='remindercampaign',
            name='conditional_rules',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='remindercampaign',
            name='is_interconnected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reminderexecution',
            name='button_response',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reminderschedule',
            name='template_variables',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='reminderexecution',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('DIVERTED', 'Diverted')], default='PENDING', max_length=20),
        ),
    ]


