# Generated by Django 5.2.7 on 2026-07-31 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_app', '0021_followupstep_template_variables_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminderschedule',
            name='button_actions',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]


