# Generated by Django 6.0.6 on 2026-08-02 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_app', '0022_reminderschedule_button_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminderexecution',
            name='selected_event_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reminderschedule',
            name='custom_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reminderschedule',
            name='message_type',
            field=models.CharField(choices=[('TEMPLATE', 'Template Message'), ('CUSTOM_TEXT', 'Custom Text/Media Message')], default='TEMPLATE', max_length=20),
        ),
        migrations.AlterField(
            model_name='reminderschedule',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminder_schedules', to='whatsapp_app.messagetemplate'),
        ),
        migrations.AlterField(
            model_name='reminderschedule',
            name='timing_type',
            field=models.CharField(choices=[('7_DAYS_BEFORE', '7 days before'), ('3_DAYS_BEFORE', '3 days before'), ('1_DAY_BEFORE', '1 day before'), ('6_HOURS_BEFORE', '6 hours before'), ('1_HOUR_BEFORE', '1 hour before'), ('15_MINS_BEFORE', '15 minutes before'), ('POST_EVENT', 'Post event follow-up'), ('CUSTOM', 'Custom timing')], max_length=30),
        ),
    ]


