# Generated by Django 6.0.6 on 2026-08-02 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_app', '0023_reminderexecution_selected_event_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reminderschedule',
            options={'ordering': ['stage_order', 'id']},
        ),
        migrations.AddField(
            model_name='remindercampaign',
            name='settings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='remindercampaign',
            name='workflow_type',
            field=models.CharField(choices=[('REMINDER', 'Event / Reminder Campaign'), ('PRODUCT_LAUNCH', 'Product Launch Campaign'), ('APPOINTMENT', 'Appointment Campaign'), ('DEMO_BOOKING', 'Demo Booking Campaign'), ('COURSE_UPDATE', 'Course Update Campaign'), ('PROMOTIONAL', 'Promotional Campaign'), ('CUSTOMER_FOLLOWUP', 'Customer Follow-up Campaign'), ('CUSTOM', 'Custom Workflow Automation')], default='REMINDER', max_length=50),
        ),
        migrations.AddField(
            model_name='reminderexecution',
            name='context_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='reminderexecution',
            name='state',
            field=models.CharField(choices=[('WAITING_INITIAL_RESPONSE', 'Waiting Initial Response'), ('WAITING_BUTTON_SELECTION', 'Waiting Button Selection'), ('WAITING_DATE_SELECTION', 'Waiting Alternate Date Selection'), ('WAITING_STAGE', 'Waiting Target Stage Execution'), ('WAITING_TIMEOUT', 'Waiting Timeout Expiration'), ('PAUSED', 'Workflow Paused'), ('COMPLETED', 'Workflow Completed'), ('EXITED', 'Workflow Exited'), ('UNSUBSCRIBED', 'Unsubscribed'), ('FAILED', 'Failed'), ('AI_HANDOVER', 'Handed over to AI Assistant')], default='WAITING_STAGE', max_length=50),
        ),
        migrations.AddField(
            model_name='reminderexecution',
            name='timeout_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reminderschedule',
            name='actions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='reminderschedule',
            name='stage_name',
            field=models.CharField(default='Broadcast Stage', max_length=255),
        ),
        migrations.AddField(
            model_name='reminderschedule',
            name='stage_order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reminderschedule',
            name='timeout_rule',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='reminderschedule',
            name='transitions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='reminderschedule',
            name='trigger_type',
            field=models.CharField(choices=[('RELATIVE_EVENT_TIME', 'Relative to Event Time'), ('DELAY_AFTER_ENTRY', 'Delay After Workflow Entry'), ('SPECIFIC_DATE_TIME', 'Specific Date and Time'), ('BUTTON_CLICK', 'Triggered on Button Click'), ('API_CALLBACK', 'Triggered on API Callback'), ('MANUAL', 'Manual Trigger')], default='RELATIVE_EVENT_TIME', max_length=50),
        ),
        migrations.AlterField(
            model_name='remindercampaign',
            name='event_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='remindercampaign',
            name='event_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='remindercampaign',
            name='event_type',
            field=models.CharField(choices=[('WEBINAR', 'Webinar'), ('EVENT', 'Event'), ('MEETING', 'Meeting'), ('APPOINTMENT', 'Appointment'), ('DEMO', 'Demo'), ('CUSTOM', 'Custom')], default='CUSTOM', max_length=20),
        ),
        migrations.AlterField(
            model_name='reminderexecution',
            name='button_response',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reminderschedule',
            name='message_type',
            field=models.CharField(choices=[('TEMPLATE', 'Template Message'), ('CUSTOM_TEXT', 'Custom Text Message'), ('MEDIA', 'Media Attachment'), ('INTERACTIVE_BUTTONS', 'Interactive Buttons'), ('INTERACTIVE_LIST', 'Interactive List'), ('ACTION_ONLY', 'Action / Condition Only')], default='TEMPLATE', max_length=30),
        ),
        migrations.AlterField(
            model_name='reminderschedule',
            name='timing_type',
            field=models.CharField(choices=[('7_DAYS_BEFORE', '7 days before'), ('3_DAYS_BEFORE', '3 days before'), ('1_DAY_BEFORE', '1 day before'), ('6_HOURS_BEFORE', '6 hours before'), ('1_HOUR_BEFORE', '1 hour before'), ('15_MINS_BEFORE', '15 minutes before'), ('POST_EVENT', 'Post event follow-up'), ('CUSTOM', 'Custom timing')], default='CUSTOM', max_length=30),
        ),
    ]


