# Generated by Django 6.0.7 on 2026-08-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_app', '0024_alter_reminderschedule_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reminderschedule',
            options={},
        ),
        migrations.RemoveField(
            model_name='reminderschedule',
            name='custom_text',
        ),
        migrations.AlterField(
            model_name='remindercampaign',
            name='event_date_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='remindercampaign',
            name='event_title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='remindercampaign',
            name='event_type',
            field=models.CharField(choices=[('WEBINAR', 'Webinar'), ('EVENT', 'Event'), ('MEETING', 'Meeting'), ('APPOINTMENT', 'Appointment'), ('DEMO', 'Demo'), ('CUSTOM', 'Custom')], max_length=20),
        ),
        migrations.AlterField(
            model_name='remindercampaign',
            name='workflow_type',
            field=models.CharField(blank=True, default='STANDARD', max_length=50),
        ),
        migrations.AlterField(
            model_name='reminderexecution',
            name='state',
            field=models.CharField(blank=True, default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='reminderschedule',
            name='actions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='reminderschedule',
            name='message_type',
            field=models.CharField(blank=True, default='TEMPLATE', max_length=30),
        ),
        migrations.AlterField(
            model_name='reminderschedule',
            name='stage_name',
            field=models.CharField(blank=True, default='Stage 1', max_length=255),
        ),
        migrations.AlterField(
            model_name='reminderschedule',
            name='stage_order',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='reminderschedule',
            name='timing_type',
            field=models.CharField(choices=[('7_DAYS_BEFORE', '7 days before'), ('5_DAYS_BEFORE', '5 days before'), ('3_DAYS_BEFORE', '3 days before'), ('2_DAYS_BEFORE', '2 days before'), ('1_DAY_BEFORE', '1 day before'), ('6_HOURS_BEFORE', '6 hours before'), ('1_HOUR_BEFORE', '1 hour before'), ('AT_EVENT_TIME', 'At Event Date & Time'), ('SPECIFIC_DATETIME', 'Specific Date & Time'), ('CUSTOM', 'Custom timing')], default='1_HOUR_BEFORE', max_length=50),
        ),
        migrations.AlterField(
            model_name='reminderschedule',
            name='trigger_type',
            field=models.CharField(blank=True, default='TIME_BEFORE', max_length=50),
        ),
    ]


