# Generated by Django 6.0.6 on 2026-08-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_app', '0025_alter_reminderschedule_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappconfig',
            name='auto_send_template',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='whatsappconfig',
            name='auto_send_template_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]


