# Generated by Django 6.0.7 on 2026-08-07 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_app', '0025_alter_reminderschedule_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contact_groups', to=settings.AUTH_USER_MODEL)),
                ('whatsapp_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_groups', to='whatsapp_app.whatsappconfig')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='contacts', to='whatsapp_app.contactgroup'),
        ),
        migrations.AddConstraint(
            model_name='contactgroup',
            constraint=models.UniqueConstraint(fields=('whatsapp_config', 'name'), name='unique_contact_group_name_per_config'),
        ),
    ]


