# Generated by Django 6.0.7 on 2026-08-10 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_app', '0026_contactgroup_contact_groups_and_more'),
        ('whatsapp_app', '0026_whatsappconfig_auto_send_template_and_more'),
    ]

    operations = [
    ]


