# Generated by Django 5.2.8 on 2026-08-12 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0188_alter_newdailyachivesmodel_client_status'),
        ('whatsapp_app', '0027_merge_20260810_1725'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTPVerification',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='team_lead',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.RenameIndex(
            model_name='messagetemplate',
            new_name='whatsapp_ap_name_9b06e1_idx',
            old_name='whatsapp_me_name_f76507_idx',
        ),
        migrations.RenameIndex(
            model_name='messagetemplate',
            new_name='whatsapp_ap_categor_5b94eb_idx',
            old_name='whatsapp_me_categor_603642_idx',
        ),
        migrations.RenameIndex(
            model_name='messagetemplate',
            new_name='whatsapp_ap_status_407c4f_idx',
            old_name='whatsapp_me_status_ec88e1_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='whatsapp_ap_is_read_14d484_idx',
            old_name='whatsapp_no_is_read_fb22f7_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='whatsapp_ap_contact_47002b_idx',
            old_name='whatsapp_no_contact_a82f41_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='whatsapp_ap_message_4fbd81_idx',
            old_name='whatsapp_no_message_f8ebd4_idx',
        ),
        migrations.RenameIndex(
            model_name='whatsapptemplate',
            new_name='whatsapp_ap_templat_1ecc1c_idx',
            old_name='whatsapp_wh_templat_7b27c4_idx',
        ),
        migrations.RenameIndex(
            model_name='whatsapptemplate',
            new_name='whatsapp_ap_status_9d1b7e_idx',
            old_name='whatsapp_wh_status_69f18b_idx',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='HRM_App.registrationmodel'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_contacts', to='HRM_App.registrationmodel'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='HRM_App.registrationmodel'),
        ),
        migrations.AlterField(
            model_name='contactgroup',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contact_groups', to='HRM_App.registrationmodel'),
        ),
        migrations.AlterField(
            model_name='followupworkflow',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_up_workflows', to='HRM_App.registrationmodel'),
        ),
        migrations.AlterField(
            model_name='loginsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wa_login_sessions', to='HRM_App.registrationmodel'),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_templates', to='HRM_App.registrationmodel'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Null means broadcast to all agents', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='HRM_App.registrationmodel'),
        ),
        migrations.AlterField(
            model_name='remindercampaign',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_campaigns', to='HRM_App.registrationmodel'),
        ),
        migrations.AlterField(
            model_name='template',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='HRM_App.registrationmodel'),
        ),
        migrations.AlterField(
            model_name='whatsappconfig',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_configs', to='HRM_App.registrationmodel'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
