# Generated by Django 5.2.8 on 2026-08-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_app', '0028_delete_otpverification_remove_user_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='button_actions',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
