# Generated by Django 5.2.8 on 2026-08-21 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_app', '0029_message_button_actions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoreply',
            name='media',
            field=models.FileField(blank=True, help_text='Optional media (e.g. PDF, image) to send with the auto-reply', null=True, upload_to='autoreplies/'),
        ),
    ]
