# Generated by Django 5.2.17 on 2026-08-25 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_app', '0030_alter_autoreply_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgedocument',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
