# Generated by Django 5.2.8 on 2026-08-18 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=255, unique=True)),
                ('app_id', models.CharField(max_length=255)),
                ('app_secret', models.CharField(max_length=255)),
                ('verify_token', models.CharField(max_length=255)),
                ('active_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FacebookLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leadgen_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('ad_id', models.CharField(blank=True, max_length=100, null=True)),
                ('ad_name', models.CharField(blank=True, max_length=255, null=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('facebook_ad_detail', models.JSONField(blank=True, null=True)),
                ('lead_gen_data', models.JSONField(blank=True, null=True)),
                ('synced', models.BooleanField(default=False)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('crm_sync', models.BooleanField(default=False)),
                ('crm_sync_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FacebookPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=255)),
                ('page_id', models.CharField(max_length=255, unique=True)),
                ('page_access_token', models.TextField()),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('generated_date', models.DateTimeField(blank=True, null=True)),
                ('active_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('allowed_ad_ids', models.JSONField(blank=True, default=list)),
                ('not_allowed_ad_ids', models.JSONField(blank=True, default=list)),
                ('auto_assign_employee', models.CharField(blank=True, max_length=100, null=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='facebook_app.facebookconfig')),
            ],
        ),
    ]
