# Generated by Django 5.2.8 on 2026-04-01 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0176_dasauthcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcandidatejoininghistory',
            name='candidate_salary',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monthly salary paid to candidate in a contract placement (includes taxes/PF)', max_digits=12),
        ),
        migrations.AddField(
            model_name='clientcandidatejoininghistory',
            name='is_contract_basis',
            field=models.BooleanField(default=False, help_text='If True, Merida pays the candidate salary (contract placement)'),
        ),
    ]
