# Generated by Django 5.2.8 on 2026-04-17 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0177_clientcandidatejoininghistory_candidate_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newdailyachivesmodel',
            name='assigned_requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HRM_App.requirementassign'),
        ),
        migrations.AlterField(
            model_name='newdailyachivesmodel',
            name='lead_status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('follow_up', 'Follow Up'), ('rejected', 'Rejected'), ('closed', 'Closed'), ('staged', 'Staged')], default='active', max_length=20, null=True),
        ),
    ]
