# Generated by Django 5.2.8 on 2026-05-25 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0178_newdailyachivesmodel_assigned_requirement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedatamodel',
            name='all_applicants_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='newdailyachivesmodel',
            name='interview_status',
            field=models.CharField(blank=True, choices=[('call_notpicked', 'Call Not Picked'), ('dis_connect', 'Disconnect'), ('will_revert_back', 'Will Revert Back'), ('interview_scheduled', 'Interview_Scheduled'), ('walkin', 'walkin'), ('rejected', 'Rejected'), ('Rejected_by_Candidate', 'Rejected_by_Candidate'), ('to_client', 'Consider_to_Client'), ('offer', 'Offer'), ('joined', 'Joined')], max_length=100, null=True),
        ),
    ]
