# Generated by Django 5.2.8 on 2026-05-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0179_employeedatamodel_all_applicants_access_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newdailyachivesmodel',
            name='sourcing_channel',
            field=models.CharField(blank=True, choices=[('direct', 'Direct'), ('website', 'Website'), ('crm', 'CRM'), ('self_adding', 'Self Adding'), ('bulk_upload', 'Bulk Upload')], db_index=True, default='direct', max_length=50, null=True),
        ),
    ]
