# Generated by Django 5.2.8 on 2026-06-02 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0180_newdailyachivesmodel_sourcing_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newdailyachivesmodel',
            name='sourcing_channel',
            field=models.CharField(blank=True, choices=[('direct', 'Direct'), ('website', 'Website'), ('crm', 'CRM'), ('facebook', 'Facebook'), ('self_adding', 'Self Adding'), ('bulk_upload', 'Bulk Upload'), ('assigned', 'Assigned')], db_index=True, default='direct', max_length=50, null=True),
        ),
    ]
