# Generated by Django 5.2.8 on 2026-06-05 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0181_alter_newdailyachivesmodel_sourcing_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screeningassigningmodel',
            name='Candidate',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Recruiter', to='HRM_App.candidateapplicationmodel'),
        ),
    ]
