# Generated by Django 5.2.8 on 2026-06-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0182_alter_screeningassigningmodel_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedatamodel',
            name='leads_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeedatamodel',
            name='universal_leads_access',
            field=models.BooleanField(default=False),
        ),
    ]
