# Generated by Django 5.2.8 on 2026-06-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0183_employeedatamodel_leads_access_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedatamodel',
            name='lead_assign_access',
            field=models.BooleanField(default=False),
        ),
    ]
