# Generated by Django 5.2.8 on 2026-07-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0184_employeedatamodel_lead_assign_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='newdailyachivesmodel',
            name='current_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newdailyachivesmodel',
            name='lead_stage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
