# Generated by Django 5.2.8 on 2026-07-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0185_newdailyachivesmodel_current_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newdailyachivesmodel',
            name='interview_attendance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
