# Generated by Django 5.2.8 on 2026-07-02 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0186_newdailyachivesmodel_interview_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='newdailyachivesmodel',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_achievements', to='HRM_App.employeedatamodel'),
        ),
    ]
