# Generated by Django 5.2.8 on 2026-08-12 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0187_newdailyachivesmodel_assigned_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newdailyachivesmodel',
            name='client_status',
            field=models.CharField(blank=True, choices=[('job', 'Job'), ('converted_to_client', 'Converted to Client'), ('closed', 'Closed'), ('followup', 'FollowUp'), ('prospect', 'Prospect')], max_length=100, null=True),
        ),
    ]
