# Generated by Django 5.2.8 on 2026-08-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0188_alter_newdailyachivesmodel_client_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedatamodel',
            name='whatsapp_access',
            field=models.BooleanField(default=False),
        ),
    ]
