# Generated by Django 5.2.8 on 2026-08-20 08:18

import HRM_App.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0189_employeedatamodel_whatsapp_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateResumeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=HRM_App.models.candidate_resume_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resume_file', to='HRM_App.candidateapplicationmodel')),
            ],
        ),
    ]
